## Data Loading/Preprocessing
* Load the following files into colab before running (Make sure they are not in a folder)
  * KenPom Barttorvik.csv
  * Preseason Votes.csv
  * Team Results.csv

### Load CSVs into DataFrames

In [20]:
import pandas as pd

#Load KenPom Barttorvik dataset into a dataframe
kenpom = pd.read_csv('KenPom Barttorvik.csv')

#Load Preseason Votes dataset into a dataframe
preseason = pd.read_csv('Preseason Votes.csv')

#Load Team Results dataset into a dataframe
team = pd.read_csv('Team Results.csv')

#Load Tournament Matchups dataset into a dataframe
matchups = pd.read_csv('Tournament Matchups.csv')

### Check Head of Each Individual CSV

In [21]:
kenpom.head()

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2024,MAC,17,61,1,1079,2,Akron,14,0,...,276,238,199,19,176,164,47,122,51,249
1,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,13,33,8,156,106,10,314,2,263,7
2,2024,P12,24,63,3,1077,8,Arizona,2,0,...,16,50,37,196,7,195,134,8,14,47
3,2024,SEC,28,64,4,1076,12,Auburn,4,0,...,58,86,76,127,69,59,284,12,8,69
4,2024,B12,7,63,3,1075,14,Baylor,3,0,...,274,31,22,304,34,97,254,15,155,1

In [22]:
preseason.head()

   YEAR  TEAM NO      TEAM  SEED  ROUND  AP VOTES  AP RANK  RANK?
0  2024   1078.0   Alabama   4.0    0.0       163       24      1
1  2024   1077.0   Arizona   2.0    0.0       776       12      1
2  2024      NaN  Arkansas   NaN    0.0       685       14      1
3  2024   1076.0    Auburn   4.0    0.0        27       31      0
4  2024   1075.0    Baylor   3.0    0.0       431       20      1

In [23]:
team.head()

,TEAM ID,TEAM,PAKE,PAKE RANK,PASE,PASE RANK,GAMES,W,L,WIN%,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,1,Abilene Christian,0.7,45,0.7,52,3,1,2,0.333,2,1,0,0,0,0,0,0,0.10%,0.00%
1,2,Akron,-0.9,179,-1.1,187,4,0,4,0.000,4,0,0,0,0,0,0,0,0.50%,0.00%
2,3,Alabama,-2.1,211,-2.9,220,10,5,5,0.500,5,3,2,0,0,0,0,2,48.40%,15.40%
3,4,Albany,-0.4,147,-0.3,138,3,0,3,0.000,3,0,0,0,0,0,0,0,0.00%,0.00%
4,6,American,-0.5,160,-0.4,150,3,0,3,0.000,3,0,0,0,0,0,0,0,0.20%,0.00%

In [24]:
matchups.head()

,YEAR,BY YEAR NO,BY ROUND NO,TEAM NO,TEAM,SEED,ROUND,CURRENT ROUND,SCORE
0,2024,2036,0,1067,Connecticut,1,1,64,NaN
1,2024,2035,0,1026,Stetson,16,64,64,NaN
2,2024,2034,0,1038,North Carolina,1,1,64,NaN
3,2024,2033,0,1055,Howard,16,64,64,NaN
4,2024,2032,0,1038,North Carolina,1,1,64,NaN

### Merge All CSVs Together

In [25]:
# Left join KenPom and Preseason based on TEAM (team name) and YEAR
first_merged_df = pd.merge(kenpom, preseason, on=['TEAM', 'YEAR'], how='left')

#Result (Makes sure all teams are loaded) (68 teams for 2024)
first_merged_df.head(100)

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO_x,TEAM ID,TEAM,SEED_x,ROUND_x,...,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK,TEAM NO_y,SEED_y,ROUND_y,AP VOTES,AP RANK,RANK?
0,2024,MAC,17,61,1,1079,2,Akron,14,0,...,47,122,51,249,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,314,2,263,7,1078.0,4.0,0.0,163.0,24.0,1.0
2,2024,P12,24,63,3,1077,8,Arizona,2,0,...,134,8,14,47,1077.0,2.0,0.0,776.0,12.0,1.0
3,2024,SEC,28,64,4,1076,12,Auburn,4,0,...,284,12,8,69,1076.0,4.0,0.0,27.0,31.0,0.0
4,2024,B12,7,63,3,1075,14,Baylor,3,0,...,254,15,155,1,1075.0,3.0,0.0,431.0,20.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023,ASun,5,58,2,984,88,Kennesaw St.,14,64,...,55,130,129,172,NaN,NaN,NaN,NaN,NaN,NaN
96,2023,MAC,17,58,2,983,89,Kent St.,13,64,...,229,63,28,158,NaN,NaN,NaN,NaN,NaN,NaN
97,2023,SEC,28,59,3,982,90,Kentucky,6,32,...,310,25,122,34,982.0,6.0,32.0,1364.0,4.0,1.0
98,2023,SB,26,59,3,981,101,Louisiana Lafayette,13,64,...,124,46,156,169,NaN,NaN,NaN,NaN,NaN,NaN
99,2023,BE,8,59,3,980,107,Marquette,2,32,...,83,14,97,28,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# Left join the KenPom/Preseason dataset and Team Dataset on TEAM (team name)
second_merged_df = pd.merge(first_merged_df, team, on='TEAM', how='left')

#Result (Makes sure all teams are loaded) (68 teams for 2024)
second_merged_df.head(100)

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO_x,TEAM ID_x,TEAM,SEED_x,ROUND_x,...,R64,R32,S16,E8,F4,F2,CHAMP,TOP2,F4%,CHAMP%
0,2024,MAC,17,61,1,1079,2,Akron,14,0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.50%,0.00%
1,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,5.0,3.0,2.0,0.0,0.0,0.0,0.0,2.0,48.40%,15.40%
2,2024,P12,24,63,3,1077,8,Arizona,2,0,...,11.0,7.0,7.0,3.0,0.0,0.0,0.0,5.0,83.50%,36.10%
3,2024,SEC,28,64,4,1076,12,Auburn,4,0,...,4.0,4.0,1.0,1.0,1.0,0.0,0.0,1.0,35.50%,6.30%
4,2024,B12,7,63,3,1075,14,Baylor,3,0,...,11.0,8.0,5.0,3.0,1.0,1.0,1.0,2.0,80.80%,33.20%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2023,ASun,5,58,2,984,88,Kennesaw St.,14,64,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.10%,0.00%
96,2023,MAC,17,58,2,983,89,Kent St.,13,64,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.10%,0.00%
97,2023,SEC,28,59,3,982,90,Kentucky,6,32,...,12.0,10.0,8.0,7.0,4.0,2.0,1.0,6.0,96.80%,63.70%
98,2023,SB,26,59,3,981,101,Louisiana Lafayette,13,64,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.30%,0.00%
99,2023,BE,8,59,3,980,107,Marquette,2,32,...,10.0,6.0,3.0,1.0,0.0,0.0,0.0,1.0,44.50%,7.80%

In [32]:
second_merged_df.shape

(1079, 128)

In [40]:
# Left join the merged dataset and the matchups dataset on TEAM (team name)
final_merged_df = pd.merge(second_merged_df, matchups, on=['TEAM', 'YEAR'], how='right')

#Result (Makes sure all teams are loaded) (68 teams for 2024)
final_merged_df.head(100)

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO_x,TEAM ID_x,TEAM,SEED_x,ROUND_x,...,TOP2,F4%,CHAMP%,BY YEAR NO,BY ROUND NO,TEAM NO,SEED,ROUND,CURRENT ROUND,SCORE
0,2024,BE,8.0,64.0,4.0,1067.0,40.0,Connecticut,1.0,0.0,...,1.0,71.10%,29.70%,2036,0,1067,1,1,64,NaN
1,2024,ASun,5.0,64.0,4.0,1026.0,250.0,Stetson,16.0,0.0,...,NaN,NaN,NaN,2035,0,1026,16,64,64,NaN
2,2024,ACC,2.0,63.0,3.0,1038.0,135.0,North Carolina,1.0,0.0,...,8.0,95.80%,54.20%,2034,0,1038,1,1,64,NaN
3,2024,MEAC,18.0,63.0,3.0,1055.0,77.0,Howard,16.0,0.0,...,0.0,0.00%,0.00%,2033,0,1055,16,64,64,NaN
4,2024,ACC,2.0,63.0,3.0,1038.0,135.0,North Carolina,1.0,0.0,...,8.0,95.80%,54.20%,2032,0,1038,1,1,64,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024,MWC,20.0,63.0,3.0,1040.0,130.0,Nevada,10.0,0.0,...,0.0,3.30%,0.20%,1941,0,1040,10,32,32,NaN
96,2024,BE,8.0,62.0,2.0,1047.0,107.0,Marquette,2.0,0.0,...,1.0,44.50%,7.80%,1940,0,1047,2,1,32,NaN
97,2024,SEC,28.0,62.0,2.0,1061.0,55.0,Florida,7.0,0.0,...,2.0,75.70%,31.20%,1939,0,1061,7,32,32,NaN
98,2024,BE,8.0,62.0,2.0,1047.0,107.0,Marquette,2.0,0.0,...,1.0,44.50%,7.80%,1938,0,1047,2,1,32,NaN
99,2024,MWC,20.0,62.0,2.0,1074.0,17.0,Boise St.,10.0,0.0,...,0.0,2.00%,0.20%,1937,0,1074,10,32,32,NaN

In [42]:
final_merged_df['CURRENT ROUND']

0       64
1       64
2       64
3       64
4       64
        ..
2031     4
2032     4
2033     4
2034     2
2035     2
Name: CURRENT ROUND, Length: 2036, dtype: int64

In [29]:
final_merged_df['CHAMP%']

0        0.00%
1        0.00%
2        0.00%
3        0.00%
4        0.00%
         ...
17658    8.70%
17659    8.70%
17660    8.70%
17661    8.70%
17662    8.70%
Name: CHAMP%, Length: 17663, dtype: object

In [35]:
final_merged_df.head(100)

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO_x,TEAM ID_x,TEAM,SEED_x,ROUND_x,...,TOP2,F4%,CHAMP%,BY YEAR NO,BY ROUND NO,TEAM NO,SEED,ROUND,CURRENT ROUND,SCORE
0,2024,MAC,17,61,1,1079,2,Akron,14,0,...,0.0,0.50%,0.00%,2009.0,0.0,1079.0,14.0,64.0,64.0,NaN
1,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,2.0,48.40%,15.40%,2006.0,0.0,1078.0,4.0,1.0,64.0,NaN
2,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,2.0,48.40%,15.40%,1910.0,0.0,1078.0,4.0,1.0,32.0,NaN
3,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,2.0,48.40%,15.40%,1899.0,0.0,1078.0,4.0,16.0,16.0,NaN
4,2024,P12,24,63,3,1077,8,Arizona,2,0,...,5.0,83.50%,36.10%,2022.0,0.0,1077.0,2.0,1.0,64.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024,ACC,2,63,3,1038,135,North Carolina,1,0,...,8.0,95.80%,54.20%,1898.0,0.0,1038.0,1.0,1.0,16.0,NaN
96,2024,ACC,2,62,2,1037,138,North Carolina St.,11,0,...,0.0,9.00%,0.50%,1987.0,0.0,1037.0,11.0,64.0,64.0,NaN
97,2024,ACC,2,62,2,1037,138,North Carolina St.,11,0,...,0.0,9.00%,0.50%,1917.0,0.0,1037.0,11.0,32.0,32.0,NaN
98,2024,B10,6,64,4,1036,147,Northwestern,9,0,...,0.0,3.00%,0.30%,1971.0,0.0,1036.0,9.0,64.0,64.0,NaN
99,2024,B10,6,64,4,1036,147,Northwestern,9,0,...,0.0,3.00%,0.30%,1961.0,0.0,1036.0,9.0,32.0,32.0,NaN

In [31]:
# Checks how many teams there are for each year (2020 tournament was cancelled)
for i in range(2024, 2008, -1):
  sum = (final_merged_df['YEAR'] == i).sum()
  print(f'{i}: {sum} teams')

KeyError: 'YEAR'